from numpy import *
arr = array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
ar1 = array([12,22,32])
ar1 = array([10,14,31])
m = matrix("1,2 ; 3,4 ; 7,6")
print(arr)
print("--------------------")
print(arr.flatten())
print("--------------------")
print(arr.shape)
print("--------------------")
print(arr.reshape(2,2,3))
print("--------------------")
print(min(m))
print("---------------------")
print(diagonal(m))
