from numpy import *
arr = array([1,2,52,47,44],float)
print(arr)
print("-----------------------------------")
arr1 = linspace(0,9,10)
print(arr1)
print("-----------------------------------")
arr1 = linspace(0,9)
print(arr1)
print("-----------------------------------")
arr1 = arange(0,9,2)
print(arr1)
print("-----------------------------------")
arr1 = logspace(0,9,2)
print(arr1)
print("-----------------------------------")
arr1 = logspace(0,9,2)
print("%.2f" %arr1[1])